## Problem 3a

The engineer explains that an engine part seems to be missing from the engine, but nobody can figure out which one. If you can add up all the part numbers in the engine schematic, it should be easy to work out which part is missing.

The engine schematic (your puzzle input) consists of a visual representation of the engine. There are lots of numbers and symbols you don't really understand, but apparently any number adjacent to a symbol, even diagonally, is a "part number" and should be included in your sum. (Periods (.) do not count as a symbol.)

Here is an example engine schematic:
```
467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598..
```
In this schematic, two numbers are not part numbers because they are not adjacent to a symbol: 114 (top right) and 58 (middle right). Every other number is adjacent to a symbol and so is a part number; their sum is 4361.

Of course, the actual engine schematic is much larger. What is the sum of all of the part numbers in the engine schematic?

**AI Prompt**

why is 35 a part number above

**AI Response**

Let's look carefully at the number 35 and its surroundings. In the schematic, 35 appears on the third line:

```
467..114..
...*......
..35..633.
```

35 is considered a part number because it is adjacent (including diagonally) to a symbol - specifically, the * that appears directly above it in the second line. 

Would you like me to show you all eight positions we need to check around any number to determine if it's a part number?

**AI Prompt**

yes

**AI Response**

For any number, we need to check these 8 positions around it (where X represents the positions to check):

```
XXX
X#X
XXX
```

Where # represents each digit of the number. So for the number 35, we're checking these positions:

```
.*. (above left, above, above right)
.35 (left, the number itself, right)
... (below left, below, below right)
```

Any symbol (except periods) in any of those X positions makes it a part number. In this case, there's a * in the "above" position, so 35 counts.

Would you like to try finding whether another number in the schematic is a part number?

In [ ]:
sample_input = '''467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598..
'''

In [ ]:
line = sample_input.splitlines()[2]

In [ ]:
line

'..35..633.'

In [ ]:
!du -sh

109M	.


In [ ]:
tri_lines = sample_input.splitlines()[1:4]
tri_lines

['...*......', '..35..633.', '......#...']

In [ ]:
for line in tri_lines:
    chars = line.split('.')
    print(chars)

['', '', '', '*', '', '', '', '', '', '']
['', '', '35', '', '633', '']
['', '', '', '', '', '', '#', '', '', '']


In [ ]:
'..35..633*.'.split('.').split('\d+')

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 1
----> 1 '..35..633*.'.split('.').split('\d+')

AttributeError: 'list' object has no attribute 'split'


AttributeError: 'list' object has no attribute 'split'

In [ ]:
line.split('.|\d+')

['......#...']

**AI Prompt**

how can i split by one or more characters in a string

**AI Response**

In Python, you can use the `re` (regular expression) module to split by multiple characters or patterns. Here's how:

```python
import re

# Example: split by either dots or digits
text = "..35..633."
parts = re.split(r'[.]|\d+', text)

# Or to split by multiple characters in one group:
parts = re.split(r'[.0-9]+', text)
```

Would you like me to explain what each part of these regular expressions means, or would you prefer to try using one of them first?

In [ ]:
import re
re.split(r'[.]|\d+', line)

['', '', '', '', '', '', '#', '', '', '']

In [ ]:
for line in tri_lines:
    chars = re.split(r'[.]|\d+', line)
    print(chars)

['', '', '', '*', '', '', '', '', '', '']
['', '', '', '', '', '', '', '']
['', '', '', '', '', '', '#', '', '', '']


In [ ]:
chars

['', '', '', '', '', '', '#', '', '', '']

In [ ]:
for line in tri_lines:
    chars = line.split('.')
    print(chars)

['', '', '', '*', '', '', '', '', '', '']
['', '', '35', '', '633', '']
['', '', '', '', '', '', '#', '', '', '']


In [ ]:
text_block = []
digits = []
row = 0
for line in tri_lines:
    chars = line.split('.')
    col = 0
    for ch in chars:
        if re.search(r'\d+', ch):
            print("found digit:", ch)
            digits.append((ch, row, col))
        col+=1
    text_block.append(chars)
    row+=1
    print(chars)

print('------')
print(text_block)
print (digits)

['', '', '', '*', '', '', '', '', '', '']
found digit: 35
found digit: 633
['', '', '35', '', '633', '']
['', '', '', '', '', '', '#', '', '', '']
------
[['', '', '', '*', '', '', '', '', '', ''], ['', '', '35', '', '633', ''], ['', '', '', '', '', '', '#', '', '', '']]
[('35', 1, 2), ('633', 1, 4)]


In [ ]:
lines = sample_input.splitlines()
text_block = []
digits = []
row = 0
for line in lines:
    chars = line.split('.')
    col = 0
    for ch in chars:
        if re.search(r'\d+', ch):
            print("found digit:", ch)
            digits.append((ch, row, col))
        col+=1
    text_block.append(chars)
    row+=1
    print(chars)

print('------')
print(text_block)
print (digits)

found digit: 467
found digit: 114
['467', '', '114', '', '']
['', '', '', '*', '', '', '', '', '', '']
found digit: 35
found digit: 633
['', '', '35', '', '633', '']
['', '', '', '', '', '', '#', '', '', '']
found digit: 617*
['617*', '', '', '', '', '', '']
found digit: 58
['', '', '', '', '', '+', '58', '']
found digit: 592
['', '', '592', '', '', '', '', '']
found digit: 755
['', '', '', '', '', '', '755', '']
['', '', '', '$', '*', '', '', '', '']
found digit: 664
found digit: 598
['', '664', '598', '', '']
------
[['467', '', '114', '', ''], ['', '', '', '*', '', '', '', '', '', ''], ['', '', '35', '', '633', ''], ['', '', '', '', '', '', '#', '', '', ''], ['617*', '', '', '', '', '', ''], ['', '', '', '', '', '+', '58', ''], ['', '', '592', '', '', '', '', ''], ['', '', '', '', '', '', '755', ''], ['', '', '', '$', '*', '', '', '', ''], ['', '664', '598', '', '']]
[('467', 0, 0), ('114', 0, 2), ('35', 2, 2), ('633', 2, 4), ('617*', 4, 0), ('58', 5, 6), ('592', 6, 2), ('755', 7, 6

In [ ]:
line = '617*......'
chars = line.split('.')
col = 0
for ch in chars:
    if re.search(r'\d+', ch):
        print("found digit:", ch)

found digit: 617*


In [ ]:
re.sub('(\d+)(.*)?', r'\1 \2', '617**afdas')

'617 **afdas'

In [ ]:
re.sub('(.*)?(\d+)(.*)?', r'\1 \2', '?617**afdas')

'?61 7'

**AI Prompt**

how to match any non digit block using re

**AI Response**

To match any non-digit characters in regex, you can use `\D+`. Here's a quick example:

```python
import re
text = "abc123xyz"
non_digits = re.findall(r'\D+', text)  # matches one or more non-digits
```

You can also use a negated character class `[^\d]+`, which means "match one or more of any character that's not a digit":

```python
non_digits = re.findall(r'[^\d]+', text)
```

Would you like me to explain the difference between these approaches, or would you like to try one first?

In [ ]:
re.sub('(\d+)(\D+)?', r'\1 \2', '?617**afdas')

'?617 **afdas'

In [ ]:
re.sub('(\D+)?(\d+)(\D+)?', r'\1 \2', '?617**afdas')

'? 617'

In [ ]:
re.sub('(\D+)?(\d+)(\D+)?', r'\1 \2 \3', '?617**afdas')

'? 617 **afdas'

In [ ]:
re.sub('(\D+)?(\d+)(\D+)?', r'\1 \2 \3', '617')

' 617 '

In [ ]:
for st in ['617', '617*', 'afs617988', '617 fasd']:
    print(re.sub('(\D+)?(\d+)(\D+)?', r'\1 \2 \3', st))

 617 
 617 *
afs 617988 
 617  fasd


In [ ]:
lines = sample_input.splitlines()
text_block = []
digits = []
row = 0
for line in lines:
    chars = line.split('.')
    col = 0
    for ch in chars:
        if re.search(r'\d+', ch):
            print("found digit:", ch)
            ch = re.sub('(\D+)?(\d+)(\D+)?', r'\1 \2 \3', ch)
            digits.append((ch, row, col))
        col+=1
    text_block.append(chars)
    row+=1
    print(chars)

print('------')
print(text_block)
print (digits)

found digit: 467
found digit: 114
['467', '', '114', '', '']
['', '', '', '*', '', '', '', '', '', '']
found digit: 35
found digit: 633
['', '', '35', '', '633', '']
['', '', '', '', '', '', '#', '', '', '']
found digit: 617*
['617*', '', '', '', '', '', '']
found digit: 58
['', '', '', '', '', '+', '58', '']
found digit: 592
['', '', '592', '', '', '', '', '']
found digit: 755
['', '', '', '', '', '', '755', '']
['', '', '', '$', '*', '', '', '', '']
found digit: 664
found digit: 598
['', '664', '598', '', '']
------
[['467', '', '114', '', ''], ['', '', '', '*', '', '', '', '', '', ''], ['', '', '35', '', '633', ''], ['', '', '', '', '', '', '#', '', '', ''], ['617*', '', '', '', '', '', ''], ['', '', '', '', '', '+', '58', ''], ['', '', '592', '', '', '', '', ''], ['', '', '', '', '', '', '755', ''], ['', '', '', '$', '*', '', '', '', ''], ['', '664', '598', '', '']]
[(' 467 ', 0, 0), (' 114 ', 0, 2), (' 35 ', 2, 2), (' 633 ', 2, 4), (' 617 *', 4, 0), (' 58 ', 5, 6), (' 592 ', 6, 2)

In [ ]:
lines = sample_input.splitlines()
text_block = []
digits = []
row = 0
for line in lines:
    print(line)
    nline = re.sub('(\D+)?(\d+)(\D+)?', r'\1\2\3', line)
    print('nline:', nline)

467..114..
nline: 467..114..
...*......
nline: ...*......
..35..633.
nline: ..35..633.
......#...
nline: ......#...
617*......
nline: 617*......
.....+.58.
nline: .....+.58.
..592.....
nline: ..592.....
......755.
nline: ......755.
...$.*....
nline: ...$.*....
.664.598..
nline: .664.598..


**AI Prompt**

how do i split this string into a the digit group and other groups

**AI Response**

To split a string into digit groups and non-digit groups, you can use re.findall with a pattern that captures both. Here's how:

```python
import re
text = "617*......"
groups = re.findall(r'(\d+|\D+)', text)
# This will give you ['617', '*', '......']
```

The pattern `(\d+|\D+)` means:
- `\d+` matches one or more digits
- `|` means "or"
- `\D+` matches one or more non-digits

Would you like to try this with your string, or would you like me to explain more about how this pattern works?

In [ ]:
import re
text = "**617*......"
groups = re.findall(r'(\d+|\D+)', text)
groups

['**', '617', '*......']

In [ ]:
groups

['**', '617', '*......']

**AI Prompt**

why do we need both \d+ and \D+ ?

**AI Response**

Let's break it down with an example:

- If we only used `\d+`, we'd only get the digit parts: `['617']`
- If we only used `\D+`, we'd only get the non-digit parts: `['**', '*......']`
- By using both `(\d+|\D+)`, we get everything in order: `['**', '617', '*......']`

This is important when we need to know both what the numbers are AND what symbols are next to them (like in your engine schematic problem, where we need to know if there are symbols adjacent to numbers).

Would you like to try some examples with different patterns to see the difference?

In [ ]:
lines = sample_input.splitlines()
text_block = []
digits = []
row = 0
for line in lines:
    print(line)
    groups = re.findall(r'((\.+|\d+)|\D+)', line)
    print('nline:', groups)

467..114..
nline: [('467', '467'), ('..', '..'), ('114', '114'), ('..', '..')]
...*......
nline: [('...', '...'), ('*......', '')]
..35..633.
nline: [('..', '..'), ('35', '35'), ('..', '..'), ('633', '633'), ('.', '.')]
......#...
nline: [('......', '......'), ('#...', '')]
617*......
nline: [('617', '617'), ('*......', '')]
.....+.58.
nline: [('.....', '.....'), ('+.', ''), ('58', '58'), ('.', '.')]
..592.....
nline: [('..', '..'), ('592', '592'), ('.....', '.....')]
......755.
nline: [('......', '......'), ('755', '755'), ('.', '.')]
...$.*....
nline: [('...', '...'), ('$.*....', '')]
.664.598..
nline: [('.', '.'), ('664', '664'), ('.', '.'), ('598', '598'), ('..', '..')]


In [ ]:
lines = sample_input.splitlines()
text_block = []
digits = []
row = 0
for line in lines:
    chars = line.split('.')
    col = 0
    for ch in chars:
        groups = re.findall(r'(\d+|\D+)', line)

        digits.append()
        if re.search(r'\d+', ch):
            print("found digit:", ch)
            digits.append((ch, row, col))
        col+=1
    text_block.append(chars)
    row+=1
    print(chars)

print('------')
print(text_block)
print (digits)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[1], line 11
      8 for ch in chars:
      9     groups = re.findall(r'(\d+|\D+)', line)
---> 11     digits.append()
     12     if re.search(r'\d+', ch):
     13         print("found digit:", ch)

TypeError: list.append() takes exactly one argument (0 given)


TypeError: list.append() takes exactly one argument (0 given)

In [ ]:
lines = sample_input.splitlines()
text_block = []
digits = []
row = 0
for line in lines:
    print(line)
    groups = re.findall(r'(\d+|\D+)', line)
    print('nline:', groups)

467..114..
nline: ['467', '..', '114', '..']
...*......
nline: ['...*......']
..35..633.
nline: ['..', '35', '..', '633', '.']
......#...
nline: ['......#...']
617*......
nline: ['617', '*......']
.....+.58.
nline: ['.....+.', '58', '.']
..592.....
nline: ['..', '592', '.....']
......755.
nline: ['......', '755', '.']
...$.*....
nline: ['...$.*....']
.664.598..
nline: ['.', '664', '.', '598', '..']


In [ ]:
lines = sample_input.splitlines()
text_block = []
digits = []
row = 0
for line in lines:
    print(line)
    chars = line.split('.') 
    for ch in chars:
        groups = re.findall(r'(\d+|\D+)', ch)
        print('nline:', groups)
        #digits.append((ch, row, col))
        col+=1
    text_block.append(chars)
    row+=1
    print(chars)

print('------')
print(text_block)
print (digits)

467..114..
nline: ['467']
nline: []
nline: ['114']
nline: []
nline: []
['467', '', '114', '', '']
...*......
nline: []
nline: []
nline: []
nline: ['*']
nline: []
nline: []
nline: []
nline: []
nline: []
nline: []
['', '', '', '*', '', '', '', '', '', '']
..35..633.
nline: []
nline: []
nline: ['35']
nline: []
nline: ['633']
nline: []
['', '', '35', '', '633', '']
......#...
nline: []
nline: []
nline: []
nline: []
nline: []
nline: []
nline: ['#']
nline: []
nline: []
nline: []
['', '', '', '', '', '', '#', '', '', '']
617*......
nline: ['617', '*']
nline: []
nline: []
nline: []
nline: []
nline: []
nline: []
['617*', '', '', '', '', '', '']
.....+.58.
nline: []
nline: []
nline: []
nline: []
nline: []
nline: ['+']
nline: ['58']
nline: []
['', '', '', '', '', '+', '58', '']
..592.....
nline: []
nline: []
nline: ['592']
nline: []
nline: []
nline: []
nline: []
nline: []
['', '', '592', '', '', '', '', '']
......755.
nline: []
nline: []
nline: []
nline: []
nline: []
nline: []
nline: ['755']
nlin

In [ ]:
re.findall(r'(\d+|.|\D+)', '617*......')

['617', '*', '.', '.', '.', '.', '.', '.']

In [ ]:
for line in lines:
    groups = re.findall(r'(\d+|.|\D+)', line)
    print(groups)

['467', '.', '.', '114', '.', '.']
['.', '.', '.', '*', '.', '.', '.', '.', '.', '.']
['.', '.', '35', '.', '.', '633', '.']
['.', '.', '.', '.', '.', '.', '#', '.', '.', '.']
['617', '*', '.', '.', '.', '.', '.', '.']
['.', '.', '.', '.', '.', '+', '.', '58', '.']
['.', '.', '592', '.', '.', '.', '.', '.']
['.', '.', '.', '.', '.', '.', '755', '.']
['.', '.', '.', '$', '.', '*', '.', '.', '.', '.']
['.', '664', '.', '598', '.', '.']


In [ ]:
curr_line = []
prev_line = []
next_line = []
part_numbers = []
row = 0
for line in lines:
    #print(line)
    groups = re.findall(r'(\d+|.|\D+)', line)
    col=0
    for group in groups:
        if re.fullmatch('\d+', group):
            #print ('partial number=', group)
            part_numbers.append((group, row, col))
        col+=1
    row+=1
    next_line = line
    prev_line = curr_line
    curr_line = prev_line
    print("kicking off tri group")
    print(prev_line)
    print(curr_line)
    print(next_line)
    #print(groups)

print (part_numbers)

kicking off tri group
[]
[]
467..114..
kicking off tri group
[]
[]
...*......
kicking off tri group
[]
[]
..35..633.
kicking off tri group
[]
[]
......#...
kicking off tri group
[]
[]
617*......
kicking off tri group
[]
[]
.....+.58.
kicking off tri group
[]
[]
..592.....
kicking off tri group
[]
[]
......755.
kicking off tri group
[]
[]
...$.*....
kicking off tri group
[]
[]
.664.598..
[('467', 0, 0), ('114', 0, 3), ('35', 2, 2), ('633', 2, 5), ('617', 4, 0), ('58', 5, 7), ('592', 6, 2), ('755', 7, 6), ('664', 9, 1), ('598', 9, 3)]


**AI Prompt**

how do i fix the code to set a triline block

**AI Response**

To create a sliding window of three lines (previous, current, and next), you can use this pattern:

```python
lines = sample_input.splitlines()
for i in range(len(lines)):
    # Get previous, current, and next lines
    prev_line = lines[i-1] if i > 0 else "." * len(lines[i])
    curr_line = lines[i]
    next_line = lines[i+1] if i < len(lines)-1 else "." * len(lines[i])
    
    print("Line group:", i)
    print(prev_line)
    print(curr_line)
    print(next_line)
```

The key points are:
- Use an index `i` to track position
- Handle edge cases (first and last lines) with padding
- Access previous line as `i-1` and next line as `i+1`

Would you like me to explain any part of this in more detail?

**AI Prompt**

i want to set these lines iteratively so i am not saving the whole lines array but saving three lines at a time

**AI Response**

Ah, to maintain just a sliding window of three lines at a time, you can use this pattern:

```python
prev_line = "." * len(lines[0])  # Initialize with dots
curr_line = "." * len(lines[0])  # Initialize with dots
next_line = None

for line in lines:
    prev_line = curr_line
    curr_line = next_line if next_line else line
    next_line = line
    
    print("Current group:")
    print(prev_line)
    print(curr_line)
    print(next_line)
```

This way you're only keeping three lines in memory at any time. Would you like me to explain how the sliding window works in this case?

**AI Prompt**

yeah explain

**AI Response**

Let's walk through how the sliding window moves, line by line:

1. Initial setup:
```
prev_line = "......."  (dots)
curr_line = "......."  (dots)
next_line = None
```

2. First iteration with line "467..114..":
```
prev_line = "......."  (previous curr_line)
curr_line = "467..114.."  (since next_line was None, we use line)
next_line = "467..114.."  (new line)
```

3. Second iteration with line "...*......":
```
prev_line = "467..114.."  (previous curr_line)
curr_line = "467..114.."  (previous next_line)
next_line = "...*......"  (new line)
```

See how each line "slides down" one position? Would you like me to continue with more iterations, or would you like to try implementing it to see it in action?

In [ ]:
curr_line = None
prev_line = None
next_line = None
row = 0
results = []
for line in lines:
    #print(line)
    groups = re.findall(r'(\d+|.|\D+)', line)
    col=0
    '''
    part_number = []
    for group in groups:
        if re.fullmatch('\d+', group):
            #print ('partial number=', group)
            part_numbers.append((group, row, col))
        col+=1
    row+=1
    '''
    prev_line = curr_line
    curr_line = next_line 
    next_line = (groups)
    print("kicking off tri group")
    print(prev_line)
    print(curr_line)
    print(next_line)

    print("testing:", curr_line)
    if not curr_line: continue
    index = 0
    for group in curr_line:
        if re.fullmatch('\d+', group):
            print ('partial number=', group)
            if not re.fullmatch('\D+', prev_line[index]): continue                    
            if not re.fullmatch('\D+', prev_line[index-1]):  continue
            if not re.fullmatch('\D+', prev_line[index+1]):  continue 
            if not re.fullmatch('\D+', curr_line[index-1]):  continue
            if not re.fullmatch('\D+', curr_line[index+1]):  continue 
            if not re.fullmatch('\D+', next_line[index]): continue                    
            if not re.fullmatch('\D+', next_line[index-1]):  continue
            if not re.fullmatch('\D+', next_line[index+1]):  continue
            part_numbers.append(group) 
            index+=1



print (part_numbers)

kicking off tri group
None
None
['467', '.', '.', '114', '.', '.']
testing: None
kicking off tri group
None
['467', '.', '.', '114', '.', '.']
['.', '.', '.', '*', '.', '.', '.', '.', '.', '.']
testing: ['467', '.', '.', '114', '.', '.']
partial number= 467
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[1], line 33
     31 if re.fullmatch('\d+', group):
     32     print ('partial number=', group)
---> 33     if not re.fullmatch('\D+', prev_line[index]): continue                    
     34     if not re.fullmatch('\D+', prev_line[index-1]):  continue
     35     if not re.fullmatch('\D+', prev_line[index+1]):  continue 

TypeError: 'NoneType' object is not subscriptable


TypeError: 'NoneType' object is not subscriptable

In [ ]:
sample_input = '''467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598..
'''

In [ ]:
group

'467'

In [ ]:
group='617'

In [ ]:
re.fullmatch('\d+', group)

<re.Match object; span=(0, 3), match='617'>

In [ ]:
re.fullmatch('\d+', group)

<re.Match object; span=(0, 3), match='617'>

**AI Prompt**

help me fix code above

**AI Response**

I see the issue. When checking adjacent positions, we need to handle the first line (when prev_line is None) and ensure we don't go out of bounds. Here's how we can fix it:

```python
curr_line = None
prev_line = None
next_line = None
row = 0
part_numbers = []

for line in lines:
    groups = re.findall(r'(\d+|.|\D+)', line)
    
    # Slide the window
    prev_line = curr_line
    curr_line = next_line 
    next_line = groups
    
    # Skip first iteration when curr_line is None
    if not curr_line: 
        continue
        
    # Use empty lists for prev_line if None
    prev_line = prev_line if prev_line else ['.'] * len(curr_line)
    
    for i, group in enumerate(curr_line):
        if re.fullmatch('\d+', group):
            # Check surrounding positions
            has_symbol = False
            
            # Check previous line
            for dx in [-1, 0, 1]:
                if 0 <= i + dx < len(prev_line):
                    if not re.fullmatch('[\d.]', prev_line[i + dx]):
                        has_symbol = True
                        
            # Check current line
            for dx in [-1, 1]:
                if 0 <= i + dx < len(curr_line):
                    if not re.fullmatch('[\d.]', curr_line[i + dx]):
                        has_symbol = True
                        
            # Check next line
            for dx in [-1, 0, 1]:
                if 0 <= i + dx < len(next_line):
                    if not re.fullmatch('[\d.]', next_line[i + dx]):
                        has_symbol = True
            
            if has_symbol:
                part_numbers.append(group)

print(part_numbers)
```

The main changes are:
1. Handle None case for prev_line
2. Use proper bounds checking (0 <= i + dx < len(line))
3. Changed the symbol check to look for anything that's not a digit or period
4. Simplified the logic to use a single has_symbol flag

Would you like me to explain any part in more detail?

In [ ]:
curr_line = None
prev_line = None
next_line = None
row = 0
results = []
for line in lines:
    #print(line)
    groups = re.findall(r'(\d+|.|\D+)', line)
    col=0
    '''
    part_number = []
    for group in groups:
        if re.fullmatch('\d+', group):
            #print ('partial number=', group)
            part_numbers.append((group, row, col))
        col+=1
    row+=1
    '''
    prev_line = curr_line
    curr_line = next_line 
    next_line = (groups)
    print("kicking off tri group")
    print(prev_line)
    print(curr_line)
    print(next_line)

    print("testing:", curr_line)
    if not curr_line: continue
    index = 0
    for (i, group) in enumerate(curr_line):
        if re.fullmatch('\d+', group):

            curr_line = None
prev_line = None
next_line = None
row = 0
results = []
for line in lines:
    #print(line)
    groups = re.findall(r'(\d+|.|\D+)', line)
    col=0
    '''
    part_number = []
    for group in groups:
        if re.fullmatch('\d+', group):
            #print ('partial number=', group)
            part_numbers.append((group, row, col))
        col+=1
    row+=1
    '''
    prev_line = curr_line
    curr_line = next_line 
    next_line = (groups)
    print("kicking off tri group")
    print(prev_line)
    print(curr_line)
    print(next_line)

    print("testing:", curr_line)
    if not curr_line: continue
    index = 0
    for (index, group) in enumerate(curr_line):
        if re.fullmatch('\d+', group):

            # Check surrounding positions
            has_symbol = False
            
            # Check previous line
            for dx in [-1, 0, 1]:
                if 0 <= i + dx < len(prev_line):
                    if not re.fullmatch('[\d+]', prev_line[i + dx]):
                        has_symbol = True

            # Check current line
            for dx in [-1, 1]:
                if 0 <= i + dx < len(curr_line):
                    if not re.fullmatch('[\d.]', curr_line[i + dx]):
                        has_symbol = True
                        
            # Check next line
            for dx in [-1, 0, 1]:
                if 0 <= i + dx < len(next_line):
                    if not re.fullmatch('[\d.]', next_line[i + dx]):
                        has_symbol = True            
            
            if has_symbol:
                part_numbers.append(group)
            
print (part_numbers)

kicking off tri group
None
None
['467', '.', '.', '114', '.', '.']
testing: None
kicking off tri group
None
['467', '.', '.', '114', '.', '.']
['.', '.', '.', '*', '.', '.', '.', '.', '.', '.']
testing: ['467', '.', '.', '114', '.', '.']
kicking off tri group
None
['.', '.', '.', '*', '.', '.', '.', '.', '.', '.']
['.', '.', '35', '.', '.', '633', '.']
testing: ['.', '.', '.', '*', '.', '.', '.', '.', '.', '.']
kicking off tri group
['.', '.', '.', '*', '.', '.', '.', '.', '.', '.']
['.', '.', '35', '.', '.', '633', '.']
['.', '.', '.', '.', '.', '.', '#', '.', '.', '.']
testing: ['.', '.', '35', '.', '.', '633', '.']
kicking off tri group
None
['.', '.', '.', '.', '.', '.', '#', '.', '.', '.']
['617', '*', '.', '.', '.', '.', '.', '.']
testing: ['.', '.', '.', '.', '.', '.', '#', '.', '.', '.']
kicking off tri group
['.', '.', '.', '.', '.', '.', '#', '.', '.', '.']
['617', '*', '.', '.', '.', '.', '.', '.']
['.', '.', '.', '.', '.', '+', '.', '58', '.']
testing: ['617', '*', '.', '.'

TypeError: object of type 'NoneType' has no len()

In [ ]:
curr_line = None
prev_line = None
next_line = None
row = 0
part_numbers = []
for line in lines:
    #print(line)
    groups = re.findall(r'(\d+|.|\D+)', line)
    col=0
    prev_line = curr_line
    curr_line = next_line 
    next_line = (groups)
    print("kicking off tri group")
    print(prev_line)
    print(curr_line)
    print(next_line)

    print("testing:", curr_line)
    if not curr_line: continue

    for (i, group) in enumerate(curr_line):
        if re.fullmatch('\d+', group):

            # Check surrounding positions
            has_symbol = False
            
            # Check previous line
            if prev_line: 
                for dx in [-1, 0, 1]:
                    if 0 <= i + dx < len(prev_line):
                        if not re.fullmatch('\d+', prev_line[i + dx]):
                            has_symbol = True
            else:
                has_symbol = True 

            # Check current line
            for dx in [-1, 1]:
                if 0 <= i + dx < len(curr_line):
                    if not re.fullmatch('\d+', curr_line[i + dx]):
                        has_symbol = True
                        
            # Check next line
            for dx in [-1, 0, 1]:
                if 0 <= i + dx < len(next_line):
                    if not re.fullmatch('\d+', next_line[i + dx]):
                        has_symbol = True            
            
            if has_symbol:
                part_numbers.append(group)
            
print (part_numbers)

kicking off tri group
None
None
['467', '.', '.', '114', '.', '.']
testing: None
kicking off tri group
None
['467', '.', '.', '114', '.', '.']
['.', '.', '.', '*', '.', '.', '.', '.', '.', '.']
testing: ['467', '.', '.', '114', '.', '.']
kicking off tri group
['467', '.', '.', '114', '.', '.']
['.', '.', '.', '*', '.', '.', '.', '.', '.', '.']
['.', '.', '35', '.', '.', '633', '.']
testing: ['.', '.', '.', '*', '.', '.', '.', '.', '.', '.']
kicking off tri group
['.', '.', '.', '*', '.', '.', '.', '.', '.', '.']
['.', '.', '35', '.', '.', '633', '.']
['.', '.', '.', '.', '.', '.', '#', '.', '.', '.']
testing: ['.', '.', '35', '.', '.', '633', '.']
kicking off tri group
['.', '.', '35', '.', '.', '633', '.']
['.', '.', '.', '.', '.', '.', '#', '.', '.', '.']
['617', '*', '.', '.', '.', '.', '.', '.']
testing: ['.', '.', '.', '.', '.', '.', '#', '.', '.', '.']
kicking off tri group
['.', '.', '.', '.', '.', '.', '#', '.', '.', '.']
['617', '*', '.', '.', '.', '.', '.', '.']
['.', '.', '.

In [ ]:
sample_input = '''467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598..
'''

**AI Prompt**

why does it not select 114 as a partial number ?

**AI Response**

Looking at the logic, there's an issue with how we're checking for symbols. Currently, we're using `re.fullmatch('\d+', prev_line[i + dx])` to check for non-symbols, which means we're only looking for digits. We should instead be checking for either digits OR periods.

Let's modify the checks to:
```python
if not re.fullmatch('[\d.]', prev_line[i + dx]):
```

This way:
- A period (.) will match
- A digit will match
- Any other character (like *) won't match, making it a symbol

The reason 114 isn't being selected is because we're treating periods as symbols right now. Would you like me to show you the corrected version of the code?

**AI Prompt**

whats difference between \d+ and [\d+] ?

**AI Response**

Let me explain the key difference:

- `\d+` means "one or more digits" (e.g., matches "123", "5", etc.)
- `[\d+]` means "a single character that is either a digit OR a plus sign" (e.g., matches "1" or "+")

The square brackets `[]` create a character class, where any single character inside the brackets will match. So:
```python
re.fullmatch('\d+', '123')    # Matches ✓
re.fullmatch('\d+', '+')      # Does not match ✗
re.fullmatch('[\d+]', '123')  # Does not match ✗
re.fullmatch('[\d+]', '+')    # Matches ✓
re.fullmatch('[\d+]', '1')    # Matches ✓
```

Would you like to try some examples to see the difference?

**AI Prompt**

whats difference between \d+ and [\d+] ?

**AI Response**

Let me explain the key difference:

- `\d+` means "one or more digits" (e.g., matches "123", "5", etc.)
- `[\d+]` means "a single character that is either a digit OR a plus sign" (e.g., matches "1" or "+")

The square brackets `[]` create a character class, where any single character inside the brackets will match. So:
```python
re.fullmatch('\d+', '123')    # Matches ✓
re.fullmatch('\d+', '+')      # Does not match ✗
re.fullmatch('[\d+]', '123')  # Does not match ✗
re.fullmatch('[\d+]', '+')    # Matches ✓
re.fullmatch('[\d+]', '1')    # Matches ✓
```

Would you like to try some examples to see the difference?

**AI Prompt**

whats difference between \d+ and [\d+] ?

**AI Response**

Let me break it down differently:

`\d+`:
- `\d` means "any digit (0-9)"
- `+` means "one or more of the previous thing"
- Together: matches one or more digits in a row (like "123", "5", "90")

`[\d+]`:
- `[]` means "match ONE character from this set"
- `\d` inside means "any digit"
- `+` inside is just a literal plus sign
- Together: matches exactly one character that is either a digit OR a plus sign (like "1" or "+" but not "123")

Would you like to see some test cases to demonstrate this?

**AI Prompt**

whats difference between \d+ and [\d+] ?

**AI Response**

Let me explain the key difference:

- `\d+` means "one or more digits" (e.g., matches "123", "5", etc.)
- `[\d+]` means "a single character that is either a digit OR a plus sign" (e.g., matches "1" or "+")

The square brackets `[]` create a character class, where any single character inside the brackets will match. So:
```python
re.fullmatch('\d+', '123')    # Matches ✓
re.fullmatch('\d+', '+')      # Does not match ✗
re.fullmatch('[\d+]', '123')  # Does not match ✗
re.fullmatch('[\d+]', '+')    # Matches ✓
re.fullmatch('[\d+]', '1')    # Matches ✓
```

Would you like to try some examples to see the difference?

In [ ]:
re.fullmatch('[\d.]+', '114 ')

In [ ]:
curr_line = None
prev_line = None
next_line = None
row = 0
part_numbers = []
for line in lines:
    #print(line)
    groups = re.findall(r'(\d+|.|\D+)', line)
    col=0
    prev_line = curr_line
    curr_line = next_line 
    next_line = (groups)
    print("kicking off tri group")
    print(prev_line)
    print(curr_line)
    print(next_line)

    print("testing:", curr_line)
    if not curr_line: continue

    for (i, group) in enumerate(curr_line):
        if re.fullmatch('\d+', group):

            # Check surrounding positions
            has_symbol = False
            
            # Check previous line
            if prev_line: 
                for dx in [-1, 0, 1]:
                    if 0 <= i + dx < len(prev_line):
                        if not re.fullmatch('[\d.]+', prev_line[i + dx]):
                            has_symbol = True
            else:
                has_symbol = True 

            # Check current line
            for dx in [-1, 1]:
                if 0 <= i + dx < len(curr_line):
                    if not re.fullmatch('[\d.]+', curr_line[i + dx]):
                        has_symbol = True
                        
            # Check next line
            for dx in [-1, 0, 1]:
                if 0 <= i + dx < len(next_line):
                    if not re.fullmatch('[\d.]+', next_line[i + dx]):
                        has_symbol = True            
            
            if has_symbol:
                part_numbers.append(group)
            
print (part_numbers)

kicking off tri group
None
None
['467', '.', '.', '114', '.', '.']
testing: None
kicking off tri group
None
['467', '.', '.', '114', '.', '.']
['.', '.', '.', '*', '.', '.', '.', '.', '.', '.']
testing: ['467', '.', '.', '114', '.', '.']
kicking off tri group
['467', '.', '.', '114', '.', '.']
['.', '.', '.', '*', '.', '.', '.', '.', '.', '.']
['.', '.', '35', '.', '.', '633', '.']
testing: ['.', '.', '.', '*', '.', '.', '.', '.', '.', '.']
kicking off tri group
['.', '.', '.', '*', '.', '.', '.', '.', '.', '.']
['.', '.', '35', '.', '.', '633', '.']
['.', '.', '.', '.', '.', '.', '#', '.', '.', '.']
testing: ['.', '.', '35', '.', '.', '633', '.']
kicking off tri group
['.', '.', '35', '.', '.', '633', '.']
['.', '.', '.', '.', '.', '.', '#', '.', '.', '.']
['617', '*', '.', '.', '.', '.', '.', '.']
testing: ['.', '.', '.', '.', '.', '.', '#', '.', '.', '.']
kicking off tri group
['.', '.', '.', '.', '.', '.', '#', '.', '.', '.']
['617', '*', '.', '.', '.', '.', '.', '.']
['.', '.', '.

In [ ]:
sample_input = '''467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598..
'''

**AI Prompt**

why is 114 geting selected in part_numbers

**AI Response**

Let's trace why 114 is being selected. In our code, 114 is on the first line:

```
467..114..
...*......
```

When checking around 114, we're looking for symbols in:
1. Previous line - doesn't exist (first line)
2. Current line - only dots
3. Next line - has a * character

The issue is in our code where we have:
```python
if prev_line: 
    for dx in [-1, 0, 1]:
        if 0 <= i + dx < len(prev_line):
            if not re.fullmatch('[\d.]+', prev_line[i + dx]):
                has_symbol = True
else:
    has_symbol = True  # <-- This is the problem!
```

We're automatically setting `has_symbol = True` when there's no previous line. We should remove that `else` clause since no previous line should be treated like a line of dots.

Would you like me to show you how to fix this?

**AI Prompt**

yes show me how to fix this

**AI Response**

Here's the corrected version - I'll just show the changed part:

```python
# Check previous line
if prev_line: 
    for dx in [-1, 0, 1]:
        if 0 <= i + dx < len(prev_line):
            if not re.fullmatch('[\d.]+', prev_line[i + dx]):
                has_symbol = True
# Remove the else clause completely
```

The rest of the code stays the same. This way, when there's no previous line, we just skip checking it rather than automatically marking the number as having a symbol.

Would you like to try running this fix to see if it correctly excludes 114?

In [ ]:
curr_line = None
prev_line = None
next_line = None
row = 0
part_numbers = []
for line in lines:
    #print(line)
    groups = re.findall(r'(\d+|.|\D+)', line)
    col=0
    prev_line = curr_line
    curr_line = next_line 
    next_line = (groups)
    print("kicking off tri group")
    print(prev_line)
    print(curr_line)
    print(next_line)

    print("testing:", curr_line)
    if not curr_line: continue

    for (i, group) in enumerate(curr_line):
        if re.fullmatch('\d+', group):
            print("checking:", i, group)
            print("curr_line:", curr_line)

            # Check surrounding positions
            has_symbol = False
            
            # Check previous line
            if prev_line: 
                print(f"Checking prev line pos {i+dx}:", prev_line[i + dx])
                if not re.fullmatch('[\d.]+', prev_line[i + dx]):
                    has_symbol = True
                    print("Found symbol in prev line!")


            # Check current line
            for dx in [-1, 1]:
                if 0 <= i + dx < len(curr_line):
                    if not re.fullmatch('[\d.]+', curr_line[i + dx]):
                        has_symbol = True
                        
            # Check next line
            for dx in [-1, 0, 1]:
                if 0 <= i + dx < len(next_line):
                    if not re.fullmatch('[\d.]+', next_line[i + dx]):
                        has_symbol = True            
            
            if has_symbol:
                part_numbers.append(group)
            
print (part_numbers)

kicking off tri group
None
None
['467', '.', '.', '114', '.', '.']
testing: None
kicking off tri group
None
['467', '.', '.', '114', '.', '.']
['.', '.', '.', '*', '.', '.', '.', '.', '.', '.']
testing: ['467', '.', '.', '114', '.', '.']
checking: 0 467
curr_line: ['467', '.', '.', '114', '.', '.']
checking: 3 114
curr_line: ['467', '.', '.', '114', '.', '.']
kicking off tri group
['467', '.', '.', '114', '.', '.']
['.', '.', '.', '*', '.', '.', '.', '.', '.', '.']
['.', '.', '35', '.', '.', '633', '.']
testing: ['.', '.', '.', '*', '.', '.', '.', '.', '.', '.']
kicking off tri group
['.', '.', '.', '*', '.', '.', '.', '.', '.', '.']
['.', '.', '35', '.', '.', '633', '.']
['.', '.', '.', '.', '.', '.', '#', '.', '.', '.']
testing: ['.', '.', '35', '.', '.', '633', '.']
checking: 2 35
curr_line: ['.', '.', '35', '.', '.', '633', '.']
Checking prev line pos 3: *
Found symbol in prev line!
checking: 5 633
curr_line: ['.', '.', '35', '.', '.', '633', '.']
Checking prev line pos 6: .
kickin

IndexError: list index out of range

**AI Prompt**

why is 114 being included

**AI Response**

Let's look at the lines around 114:
```
467..114..  <-- 114 is here
...*......  <-- there's a * below
```

Looking at our code, we're checking:
1. Previous line (skipped since none exists)
2. Current line (checks for symbols left and right of 114)
3. Next line (checks for symbols below, including diagonally)

The * in the next line at position 3 should be affecting 114 since it's diagonally adjacent. Let's debug by adding some print statements to see exactly what's being checked. Would you like me to show you how to add debug prints to see why 114 is being marked as having an adjacent symbol?

In [ ]:
curr_line= ['467', '.', '.', '114', '.', '.']
re.fullmatch('[\d.]+', curr_line[-1])

<re.Match object; span=(0, 1), match='.'>

**AI Prompt**

yes lets add some print statements. please suggest where

**AI Response**

Let's add print statements in three key places to track what's happening when we check around 114. Here's where to add them:

```python
for (i, group) in enumerate(curr_line):
    if re.fullmatch('\d+', group):
        print("\nChecking number:", group, "at position:", i)
        
        # Check surrounding positions
        has_symbol = False
        
        # Check previous line
        if prev_line: 
            for dx in [-1, 0, 1]:
                if 0 <= i + dx < len(prev_line):
                    print(f"Checking prev line pos {i+dx}:", prev_line[i + dx])
                    if not re.fullmatch('[\d.]+', prev_line[i + dx]):
                        has_symbol = True
                        print("Found symbol in prev line!")

        # Check current line
        for dx in [-1, 1]:
            if 0 <= i + dx < len(curr_line):
                print(f"Checking curr line pos {i+dx}:", curr_line[i + dx])
                if not re.fullmatch('[\d.]+', curr_line[i + dx]):
                    has_symbol = True
                    print("Found symbol in curr line!")
                    
        # Check next line
        for dx in [-1, 0, 1]:
            if 0 <= i + dx < len(next_line):
                print(f"Checking next line pos {i+dx}:", next_line[i + dx])
                if not re.fullmatch('[\d.]+', next_line[i + dx]):
                    has_symbol = True
                    print("Found symbol in next line!")
```

Would you like to try running this modified version to see what it tells us about 114?

In [ ]:
for (i, group) in enumerate(curr_line):
    if re.fullmatch('\d+', group):
        print("\nChecking number:", group, "at position:", i)
        
        # Check surrounding positions
        has_symbol = False
        
        # Check previous line
        if prev_line: 
            for dx in [-1, 0, 1]:
                if 0 <= i + dx < len(prev_line):
                    print(f"Checking prev line pos {i+dx}:", prev_line[i + dx])
                    if not re.fullmatch('[\d.]+', prev_line[i + dx]):
                        has_symbol = True
                        print("Found symbol in prev line!")

        # Check current line
        for dx in [-1, 1]:
            if 0 <= i + dx < len(curr_line):
                print(f"Checking curr line pos {i+dx}:", curr_line[i + dx])
                if not re.fullmatch('[\d.]+', curr_line[i + dx]):
                    has_symbol = True
                    print("Found symbol in curr line!")
                    
        # Check next line
        for dx in [-1, 0, 1]:
            if 0 <= i + dx < len(next_line):
                print(f"Checking next line pos {i+dx}:", next_line[i + dx])
                if not re.fullmatch('[\d.]+', next_line[i + dx]):
                    has_symbol = True
                    print("Found symbol in next line!")


Checking number: 467 at position: 0
Checking prev line pos 0: 617
Checking prev line pos 1: *
Found symbol in prev line!
Checking curr line pos 1: .
Checking next line pos 0: .
Checking next line pos 1: .

Checking number: 114 at position: 3
Checking prev line pos 2: .
Checking prev line pos 3: .
Checking prev line pos 4: .
Checking curr line pos 2: .
Checking curr line pos 4: .
Checking next line pos 2: 592
Checking next line pos 3: .
Checking next line pos 4: .


**AI Prompt**

curr_line = None
prev_line = None
next_line = None
row = 0
part_numbers = []
for line in lines:
    #print(line)
    groups = re.findall(r'(\d+|.|\D+)', line)
    col=0
    prev_line = curr_line
    curr_line = next_line 
    next_line = (groups)
    print("kicking off tri group")
    print(prev_line)
    print(curr_line)
    print(next_line)

    print("testing:", curr_line)
    if not curr_line: continue

    for (i, group) in enumerate(curr_line):
        if re.fullmatch('\d+', group):
            print("checking:", i, group)
            print("curr_line:", curr_line)

            # Check surrounding positions
            has_symbol = False
            
            # Check previous line
            if prev_line: 
                print(f"Checking prev line pos {i+dx}:", prev_line[i + dx])
                if not re.fullmatch('[\d.]+', prev_line[i + dx]):
                    has_symbol = True
                    print("Found symbol in prev line!")


            # Check current line
            for dx in [-1, 1]:
                if 0 <= i + dx < len(curr_line):
                    if not re.fullmatch('[\d.]+', curr_line[i + dx]):
                        has_symbol = True
                        
            # Check next line
            for dx in [-1, 0, 1]:
                if 0 <= i + dx < len(next_line):
                    if not re.fullmatch('[\d.]+', next_line[i + dx]):
                        has_symbol = True            
            
            if has_symbol:
                part_numbers.append(group)
            
print (part_numbers)
  

can u add print statements to above print block to help debugging

**AI Response**

Here's the code with added print statements to help debug what's happening at each check:

```python
for (i, group) in enumerate(curr_line):
    if re.fullmatch('\d+', group):
        print("\nChecking number:", group, "at position:", i)
        print("Current line layout:", curr_line)
        
        # Check surrounding positions
        has_symbol = False
        
        # Check previous line
        if prev_line: 
            print("Checking previous line:", prev_line)
            for dx in [-1, 0, 1]:
                if 0 <= i + dx < len(prev_line):
                    print(f"  Prev line pos {i+dx}:", prev_line[i + dx])
                    if not re.fullmatch('[\d.]+', prev_line[i + dx]):
                        has_symbol = True
                        print("  Found symbol in prev line!")

        # Check current line
        print("Checking current line positions:")
        for dx in [-1, 1]:
            if 0 <= i + dx < len(curr_line):
                print(f"  Curr line pos {i+dx}:", curr_line[i + dx])
                if not re.fullmatch('[\d.]+', curr_line[i + dx]):
                    has_symbol = True
                    print("  Found symbol in curr line!")
                    
        # Check next line
        print("Checking next line:", next_line)
        for dx in [-1, 0, 1]:
            if 0 <= i + dx < len(next_line):
                print(f"  Next line pos {i+dx}:", next_line[i + dx])
                if not re.fullmatch('[\d.]+', next_line[i + dx]):
                    has_symbol = True
                    print("  Found symbol in next line!")
        
        print("Has symbol:", has_symbol)

        if has_symbol:
            part_numbers.append(group)
```

This will show us:
1. Which number we're checking and its position
2. The complete layout of each line we're checking
3. Each position being checked and its content
4. When a symbol is found
5. The final decision for each number

Would you like to run this version to see the detailed output?

In [ ]:
curr_line = None
prev_line = None
next_line = None
row = 0
part_numbers = []
for line in lines:
    #print(line)
    groups = re.findall(r'(\d|.|\D)', line)
    col=0
    prev_line = curr_line
    curr_line = next_line 
    next_line = (groups)
    print("\nkicking off tri group")
    print(prev_line)
    print(curr_line)
    print(next_line)

    print("testing:", curr_line)
    if not curr_line: continue

    for (i, group) in enumerate(curr_line):
        if re.fullmatch('\d+', group):
            print("\nChecking number:", group, "at position:", i)
            #print("Current line layout:", curr_line)
            
            # Check surrounding positions
            has_symbol = False
            
            # Check previous line
            if prev_line: 
                #print("Checking previous line:", prev_line)
                for dx in [-1, 0, 1]:
                    if 0 <= i + dx < len(prev_line):
                        #print(f"  Prev line pos {i+dx}:", prev_line[i + dx])
                        if not re.fullmatch('[\d.]+', prev_line[i + dx]):
                            has_symbol = True
                            print("  Found symbol in prev line!")

            # Check current line
            #print("Checking current line positions:")
            for dx in [-1, 1]:
                if 0 <= i + dx < len(curr_line):
                    #print(f"  Curr line pos {i+dx}:", curr_line[i + dx])
                    if not re.fullmatch('[\d.]+', curr_line[i + dx]):
                        has_symbol = True
                        print("  Found symbol in curr line!")
                        
            # Check next line
            #print("Checking next line:", next_line)
            for dx in [-1, 0, 1]:
                if 0 <= i + dx < len(next_line):
                    #print(f"  Next line pos {i+dx}:", next_line[i + dx])
                    if not re.fullmatch('[\d.]+', next_line[i + dx]):
                        has_symbol = True
                        print("  Found symbol in next line!")
            
            print("Has symbol:", has_symbol)

            if has_symbol:
                part_numbers.append(group)
print (part_numbers)


kicking off tri group
None
None
['4', '6', '7', '.', '.', '1', '1', '4', '.', '.']
testing: None

kicking off tri group
None
['4', '6', '7', '.', '.', '1', '1', '4', '.', '.']
['.', '.', '.', '*', '.', '.', '.', '.', '.', '.']
testing: ['4', '6', '7', '.', '.', '1', '1', '4', '.', '.']

Checking number: 4 at position: 0
Has symbol: False

Checking number: 6 at position: 1
Has symbol: False

Checking number: 7 at position: 2
  Found symbol in next line!
Has symbol: True

Checking number: 1 at position: 5
Has symbol: False

Checking number: 1 at position: 6
Has symbol: False

Checking number: 4 at position: 7
Has symbol: False

kicking off tri group
['4', '6', '7', '.', '.', '1', '1', '4', '.', '.']
['.', '.', '.', '*', '.', '.', '.', '.', '.', '.']
['.', '.', '3', '5', '.', '.', '6', '3', '3', '.']
testing: ['.', '.', '.', '*', '.', '.', '.', '.', '.', '.']

kicking off tri group
['.', '.', '.', '*', '.', '.', '.', '.', '.', '.']
['.', '.', '3', '5', '.', '.', '6', '3', '3', '.']
['.',

In [ ]:
re.fullmatch('[\d.]+', '.')

<re.Match object; span=(0, 1), match='.'>

**AI Prompt**

aargh i am totally lost. help

**AI Response**

Let's start fresh and break down the problem:

1. First, I notice we made a mistake in how we're splitting the input. Instead of:
```python
groups = re.findall(r'(\d|.|\D)', line)  # This splits every single character
```
We should use:
```python
groups = re.findall(r'(\d+|.)', line)  # This keeps numbers together
```

2. Let's make a simpler version focusing on just the first few lines:
```python
lines = """467..114..
...*......
..35..633.""".splitlines()

# Let's print exactly what we're looking at
for i, line in enumerate(lines):
    print(f"Line {i}: {line}")
```

Would you like me to help you build a clearer solution step by step?

**AI Prompt**

yes please

**AI Response**

Okay, let's build this step by step. First, let's just focus on getting our three lines and splitting them correctly:

```python
lines = """467..114..
...*......
..35..633.""".splitlines()

# Step 1: Just print each line and see how re.findall splits it
for i, line in enumerate(lines):
    groups = re.findall(r'(\d+|.)', line)
    print(f"Line {i}: {line}")
    print(f"Split into: {groups}")
```

Run this and let me know when you're ready to look at the output and move to the next step.

In [ ]:
lines = """467..114..
...*......
..35..633.""".splitlines()
for i, line in enumerate(lines):
    groups = re.findall(r'(\d+|.)', line)
    print(f"Line {i}: {line}")
    print(f"Split into: {groups}")

Line 0: 467..114..
Split into: ['467', '.', '.', '114', '.', '.']
Line 1: ...*......
Split into: ['.', '.', '.', '*', '.', '.', '.', '.', '.', '.']
Line 2: ..35..633.
Split into: ['.', '.', '35', '.', '.', '633', '.']


**AI Prompt**

ok but then later on i have to find the index next to each number by accounting for the numeric length of the group.

**AI Response**

Ah, good point! When we split like this, we lose the actual position of each number in the original string. Let's modify our approach to keep track of the positions:

```python
lines = """467..114..
...*......
..35..633.""".splitlines()

# Step 1: Find numbers and their positions in each line
for i, line in enumerate(lines):
    # Find all numbers and their positions
    for match in re.finditer(r'\d+', line):
        number = match.group()
        start_pos = match.start()
        end_pos = match.end()
        print(f"Line {i}: number {number} from position {start_pos} to {end_pos}")
```

This will show us exactly where each number starts and ends in the original line. Would you like to run this and see how it helps with finding adjacent positions?

In [ ]:
curr_line = None
prev_line = None
next_line = None
row = 0
part_numbers = []
for line in lines:
    #print(line)   
    col=0
    prev_line = curr_line
    curr_line = next_line 
    next_line = line
    #next_line = (groups)
    print("\nkicking off tri group")
    print(prev_line)
    print(curr_line)
    print(next_line)

    print("testing:", curr_line)
    if not curr_line: continue

    groups = re.findall(r'(\d+|.|\D+)', curr_line)
    for (i, group) in enumerate(groups):

        if re.fullmatch('\d+', group):
            print("\nChecking number:", group, "at position:", i)
            #print("Current line layout:", curr_line)
 
            # Check surrounding positions
            has_symbol = False
            
            # Check previous line
            if prev_line: 
                #print("Checking previous line:", prev_line)
                for dx in [-1, 0, 1]:
                    if 0 <= i + dx < len(prev_line):
                        #print(f"  Prev line pos {i+dx}:", prev_line[i + dx])
                        if not re.fullmatch('[\d.]+', prev_line[i + dx]):
                            has_symbol = True
                            print("  Found symbol in prev line!")

            # Check current line
            #print("Checking current line positions:")
            for dx in [-1, 1]:
                if 0 <= i + dx < len(curr_line):
                    #print(f"  Curr line pos {i+dx}:", curr_line[i + dx])
                    if not re.fullmatch('[\d.]+', curr_line[i + dx]):
                        has_symbol = True
                        print("  Found symbol in curr line!")
                        
            # Check next line
            #print("Checking next line:", next_line)
            for dx in [-1, 0, 1]:
                if 0 <= i + dx < len(next_line):
                    #print(f"  Next line pos {i+dx}:", next_line[i + dx])
                    if not re.fullmatch('[\d.]+', next_line[i + dx]):
                        has_symbol = True
                        print("  Found symbol in next line!")
            
            print("Has symbol:", has_symbol)

            if has_symbol:
                part_numbers.append(group)
print (part_numbers)


kicking off tri group
None
None
467..114..
testing: None

kicking off tri group
None
467..114..
...*......
testing: 467..114..

Checking number: 467 at position: 0
Has symbol: False

Checking number: 114 at position: 3
  Found symbol in next line!
Has symbol: True

kicking off tri group
467..114..
...*......
..35..633.
testing: ...*......
['114']


In [ ]:
ll='467..114..'
re.fullmatch('[\d.]+', ll)

<re.Match object; span=(0, 10), match='467..114..'>

In [ ]:
re.finditer('[\d.]+', ll)

In [ ]:
for match in re.finditer(r'\d+', ll):
        number = match.group()
        start_pos = match.start()
        end_pos = match.end()
        print(f"Line {i}: number {number} from position {start_pos} to {end_pos}")

Line 9: number 467 from position 0 to 3
Line 9: number 114 from position 5 to 8


In [ ]:
curr_line = None
prev_line = None
next_line = None
row = 0
part_numbers = []
for line in lines:
    #print(line)   
    col=0
    prev_line = curr_line
    curr_line = next_line 
    next_line = line
    #next_line = (groups)
    print("\nkicking off tri group")
    print(prev_line)
    print(curr_line)
    print(next_line)

    print("testing:", curr_line)
    if not curr_line: continue

    '''
    groups = re.findall(r'(\d+|.|\D+)', curr_line)
    for (i, group) in enumerate(groups):
    '''
    for match in re.finditer(r'\d+', ll):
        number = match.group()
        start_pos = match.start()
        end_pos = match.end()
        print(f"Line {i}: number {number} from position {start_pos} to {end_pos}")
     
        # Check surrounding positions
        has_symbol = False
            
        # Check previous line
        if prev_line: 
            #print("Checking previous line:", prev_line)
            for dx in [-1, 0, 1]:
                if 0 <= i + dx < len(prev_line):
                    #print(f"  Prev line pos {i+dx}:", prev_line[i + dx])
                    if not re.fullmatch('[\d.]+', prev_line[i + dx]):
                        has_symbol = True
                        print("  Found symbol in prev line!")

        # Check current line
        #print("Checking current line positions:")
        for dx in [-1, 1]:
            if 0 <= i + dx < len(curr_line):
                #print(f"  Curr line pos {i+dx}:", curr_line[i + dx])
                if not re.fullmatch('[\d.]+', curr_line[i + dx]):
                    has_symbol = True
                    print("  Found symbol in curr line!")
                        
        # Check next line
        #print("Checking next line:", next_line)
        for dx in [-1, 0, 1]:
            if 0 <= i + dx < len(next_line):
                #print(f"  Next line pos {i+dx}:", next_line[i + dx])
                if not re.fullmatch('[\d.]+', next_line[i + dx]):
                    has_symbol = True
                    print("  Found symbol in next line!")
            
        print("Has symbol:", has_symbol)

        if has_symbol:
            part_numbers.append(group)
print (part_numbers)


kicking off tri group
None
None
467..114..
testing: None

kicking off tri group
None
467..114..
...*......
testing: 467..114..
Line 9: number 467 from position 0 to 3
Has symbol: False
Line 9: number 114 from position 5 to 8
Has symbol: False

kicking off tri group
467..114..
...*......
..35..633.
testing: ...*......
Line 9: number 467 from position 0 to 3
Has symbol: False
Line 9: number 114 from position 5 to 8
Has symbol: False
[]


**AI Prompt**

how can i left shift lines in the code tab

**AI Response**

To shift code left (unindent) in most code editors, you can:

1. Select the lines you want to shift
2. Press `Shift + Tab`

If you're asking about the Python code itself, you can remove indentation by deleting spaces/tabs at the start of the lines. Would you like me to help you reorganize any specific part of the code?

In [ ]:
curr_line = None
prev_line = None
next_line = None
row = 0
part_numbers = []
for line in lines:
    #print(line)   
    col=0
    prev_line = curr_line
    curr_line = next_line 
    next_line = line
    #next_line = (groups)
    print("\nkicking off tri group")
    print(prev_line)
    print(curr_line)
    print(next_line)

    print("testing:", curr_line)
    if not curr_line: continue

    '''
    groups = re.findall(r'(\d+|.|\D+)', curr_line)
    for (i, group) in enumerate(groups):
    '''
    for match in re.finditer(r'\d+', ll):
        number = match.group()
        start_pos = match.start()
        end_pos = match.end()
        print(f"Line {i}: number {number} from position {start_pos} to {end_pos}")
     
        # Check surrounding positions
        has_symbol = False
            
        # Check previous line
        if prev_line: 
            #print("Checking previous line:", prev_line)
            for dx in range(start_pos, end_pos):
            #for dx in [-1, 0, 1]:
                if 0 <= start_pos + dx < len(prev_line):
                    print(f"  Prev line pos {i+dx}:", prev_line[i + dx])
                    if not re.fullmatch('[\d.]+', prev_line[i + dx]):
                        has_symbol = True
                        print("  Found symbol in prev line!")

        # Check current line
        #print("Checking current line positions:")
        for dx in [-1, 1]:
            if 0 <= i + dx < len(curr_line):
                #print(f"  Curr line pos {i+dx}:", curr_line[i + dx])
                if not re.fullmatch('[\d.]+', curr_line[i + dx]):
                    has_symbol = True
                    print("  Found symbol in curr line!")
                        
        # Check next line
        #print("Checking next line:", next_line)
        for dx in [-1, 0, 1]:
            if 0 <= i + dx < len(next_line):
                #print(f"  Next line pos {i+dx}:", next_line[i + dx])
                if not re.fullmatch('[\d.]+', next_line[i + dx]):
                    has_symbol = True
                    print("  Found symbol in next line!")
            
        print("Has symbol:", has_symbol)

        if has_symbol:
            part_numbers.append(group)
print (part_numbers)


kicking off tri group
None
None
467..114..
testing: None

kicking off tri group
None
467..114..
...*......
testing: 467..114..
Line 9: number 467 from position 0 to 3
Has symbol: False
Line 9: number 114 from position 5 to 8
Has symbol: False

kicking off tri group
467..114..
...*......
..35..633.
testing: ...*......
Line 9: number 467 from position 0 to 3
  Prev line pos 9: .
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[1], line 40
     37 for dx in range(start_pos, end_pos):
     38 #for dx in [-1, 0, 1]:
     39     if 0 <= start_pos + dx < len(prev_line):
---> 40         print(f"  Prev line pos {i+dx}:", prev_line[i + dx])
     41         if not re.fullmatch('[\d.]+', prev_line[i + dx]):
     42             has_symbol = True

IndexError: string index out of range


IndexError: string index out of range

In [ ]:
start_pos = 0
end_pos = 3
range(start_pos-1, end_pos+1)

range(-1, 4)

**AI Prompt**

can u help me oiut here

**AI Response**

Let's clean up and fix the code. Here's a clearer approach:

```python
curr_line = None
prev_line = None
next_line = None
part_numbers = []

for line in lines:
    # Slide our window of 3 lines
    prev_line = curr_line
    curr_line = next_line 
    next_line = line

    if not curr_line: 
        continue

    # Find numbers in current line
    for match in re.finditer(r'\d+', curr_line):
        number = match.group()
        start = match.start()
        end = match.end()
        
        print(f"\nChecking number {number} from pos {start} to {end}")
        has_symbol = False

        # Check positions around the number
        # We need to check positions start-1 to end+1 in all three lines
        for row_offset in [-1, 0, 1]:
            check_line = prev_line if row_offset == -1 else curr_line if row_offset == 0 else next_line
            if check_line:
                # Look at the positions around the number
                for pos in range(start-1, end+1):
                    if 0 <= pos < len(check_line):
                        char = check_line[pos]
                        print(f"  Checking {char} at pos {pos} in {'prev' if row_offset==-1 else 'curr' if row_offset==0 else 'next'} line")
                        if char != '.' and not char.isdigit():
                            has_symbol = True
                            
        if has_symbol:
            part_numbers.append(number)

print("Part numbers found:", part_numbers)
```

Would you like me to explain how this version works? The main changes are:
1. Using string positions directly instead of split groups
2. Checking actual characters around the number
3. Using a simpler way to check for symbols (anything that's not a dot or digit)

**AI Prompt**

waht does row offset do in the above code ?

**AI Response**

Let me explain row_offset with a visual example:

When we're checking around a number (let's say "467"):
```
row_offset = -1   checks the line above    (prev_line)
row_offset = 0    checks the current line  (curr_line)
row_offset = 1    checks the line below    (next_line)
```

So if we're looking at this part of the schematic:
```
...*......  <-- prev_line   (row_offset = -1)
..35..633.  <-- curr_line   (row_offset = 0)
......#...  <-- next_line   (row_offset = 1)
```

The line `check_line = prev_line if row_offset == -1 else curr_line if row_offset == 0 else next_line` is just choosing which of these three lines to look at.

Would you like me to show what positions it checks for a specific number?

In [ ]:
curr_line = None
prev_line = None
next_line = None
row = 0
part_numbers = []
for line in lines:
    #print(line)   
    col=0
    prev_line = curr_line
    curr_line = next_line 
    next_line = line
    #next_line = (groups)
    print("\nkicking off tri group")
    print(prev_line)
    print(curr_line)
    print(next_line)

    print("testing:", curr_line)
    if not curr_line: continue

    '''
    groups = re.findall(r'(\d+|.|\D+)', curr_line)
    for (i, group) in enumerate(groups):
    '''
    for match in re.finditer(r'\d+', ll):
        number = match.group()
        start_pos = match.start()
        end_pos = match.end()
        print(f"Line {i}: number {number} from position {start_pos} to {end_pos}")
     
        # Check surrounding positions
        has_symbol = False
            
        for check_line in [prev_line, curr_line, next_line]:
            if not check_line: continue
            for pos in range(start_pos-1, end_pos+1):
                if 0<=pos<len(check_line):
                    char = check_line[pos]
                    print(f"  Checking {char} at pos {pos} in: {check_line}")
                    if char != '.' and not char.isdigit():
                        has_symbol = True
                        print("  Found symbol")

        print("Has symbol:", has_symbol)

        if has_symbol:
            part_numbers.append(number)
print (part_numbers)


kicking off tri group
None
None
467..114..
testing: None

kicking off tri group
None
467..114..
...*......
testing: 467..114..
Line 9: number 467 from position 0 to 3
  Checking 4 at pos 0 in: 467..114..
  Checking 6 at pos 1 in: 467..114..
  Checking 7 at pos 2 in: 467..114..
  Checking . at pos 3 in: 467..114..
  Checking . at pos 0 in: ...*......
  Checking . at pos 1 in: ...*......
  Checking . at pos 2 in: ...*......
  Checking * at pos 3 in: ...*......
  Found symbol
Has symbol: True
Line 9: number 114 from position 5 to 8
  Checking . at pos 4 in: 467..114..
  Checking 1 at pos 5 in: 467..114..
  Checking 1 at pos 6 in: 467..114..
  Checking 4 at pos 7 in: 467..114..
  Checking . at pos 8 in: 467..114..
  Checking . at pos 4 in: ...*......
  Checking . at pos 5 in: ...*......
  Checking . at pos 6 in: ...*......
  Checking . at pos 7 in: ...*......
  Checking . at pos 8 in: ...*......
Has symbol: False

kicking off tri group
467..114..
...*......
..35..633.
testing: ...*......


**AI Prompt**

help debug that line

**AI Response**

The line has a missing quotation mark at the end. Here's the corrected line:

```python
print(f"  Checking {char} at pos {pos} in: {check_line}")
```

The error was because we had an opening quote but no closing quote. Would you like me to show you the complete fixed code block?

In [ ]:
curr_line = None
prev_line = None
next_line = None
row = 0
part_numbers = []
lines.append(None)
lines.append(None)

for line in lines:
    #print(line)   
    col=0
    prev_line = curr_line
    curr_line = next_line 
    next_line = line
    #next_line = (groups)
    print("\nkicking off tri group")
    print(prev_line)
    print(curr_line)
    print(next_line)

    print("testing:", curr_line)
    if not curr_line: continue

    for match in re.finditer(r'\d+', curr_line):
        number = match.group()
        start_pos = match.start()
        end_pos = match.end()
        print(f"Line {i}: number {number} from position {start_pos} to {end_pos}")
     
        # Check surrounding positions
        has_symbol = False
            
        for check_line in [prev_line, curr_line, next_line]:
            if not check_line: continue
            for pos in range(start_pos-1, end_pos+1):
                if 0<=pos<len(check_line):
                    char = check_line[pos]
                    print(f"  Checking {char} at pos {pos} in: {check_line}")
                    if char != '.' and not char.isdigit():
                        has_symbol = True
                        print("  Found symbol")

        print("Has symbol:", has_symbol)

        if has_symbol:
            part_numbers.append(number)
print (part_numbers)

result = sum(int(pn) for pn in part_numbers)
print (f"summed result: {result}")


kicking off tri group
None
None
467..114..
testing: None

kicking off tri group
None
467..114..
...*......
testing: 467..114..
Line 9: number 467 from position 0 to 3
  Checking 4 at pos 0 in: 467..114..
  Checking 6 at pos 1 in: 467..114..
  Checking 7 at pos 2 in: 467..114..
  Checking . at pos 3 in: 467..114..
  Checking . at pos 0 in: ...*......
  Checking . at pos 1 in: ...*......
  Checking . at pos 2 in: ...*......
  Checking * at pos 3 in: ...*......
  Found symbol
Has symbol: True
Line 9: number 114 from position 5 to 8
  Checking . at pos 4 in: 467..114..
  Checking 1 at pos 5 in: 467..114..
  Checking 1 at pos 6 in: 467..114..
  Checking 4 at pos 7 in: 467..114..
  Checking . at pos 8 in: 467..114..
  Checking . at pos 4 in: ...*......
  Checking . at pos 5 in: ...*......
  Checking . at pos 6 in: ...*......
  Checking . at pos 7 in: ...*......
  Checking . at pos 8 in: ...*......
Has symbol: False

kicking off tri group
467..114..
...*......
..35..633.
testing: ...*......


In [ ]:
lines= sample_input.splitlines()

## Final solution to Part 1

In [ ]:
os.environ['AOC_SESSION'] = '53616c7465645f5fb344d5631fd38994e76ca613dca9a5c84c0e20e1c3cff65206ce26c3833714663d7a57036891ac56cd74a3e151b23654006ac978993e2cce'

In [ ]:
from aocd import get_data
inp = get_data(day=3, year=2023)
inp[:50]

'.......358..........31.....339.....669............'

In [ ]:
import re
curr_line = None
prev_line = None
next_line = None
part_numbers = []

lines = inp.splitlines()
lines.append(None)
lines.append(None)

for line in lines:
    #print(line)   
    col=0
    prev_line = curr_line
    curr_line = next_line 
    next_line = line
    #next_line = (groups)
    print("\nkicking off tri group")
    print(prev_line)
    print(curr_line)
    print(next_line)

    print("testing:", curr_line)
    if not curr_line: continue

    for match in re.finditer(r'\d+', curr_line):
        number = match.group()
        start_pos = match.start()
        end_pos = match.end()
        print(f"Line : number {number} from position {start_pos} to {end_pos}")
     
        # Check surrounding positions
        has_symbol = False
            
        for check_line in [prev_line, curr_line, next_line]:
            if not check_line: continue
            for pos in range(start_pos-1, end_pos+1):
                if 0<=pos<len(check_line):
                    char = check_line[pos]
                    print(f"  Checking {char} at pos {pos} in: {check_line}")
                    if char != '.' and not char.isdigit():
                        has_symbol = True
                        print("  Found symbol")

        print("Has symbol:", has_symbol)

        if has_symbol:
            part_numbers.append(number)
print (part_numbers)

result = sum(int(pn) for pn in part_numbers)
print (f"summed result: {result}")


kicking off tri group
None
None
.......358..........31.....339.....669.............598......328.....575......................447..650..............964...........692........
testing: None

kicking off tri group
None
.......358..........31.....339.....669.............598......328.....575......................447..650..............964...........692........
...............415..*.........@......*...627*...................945*.............144/.506............................*......514...*...150...
testing: .......358..........31.....339.....669.............598......328.....575......................447..650..............964...........692........
Line : number 358 from position 7 to 10
  Checking . at pos 6 in: .......358..........31.....339.....669.............598......328.....575......................447..650..............964...........692........
  Checking 3 at pos 7 in: .......358..........31.....339.....669.............598......328.....575......................447..650..............964.

## Part 2 

The missing part wasn't the only issue - one of the gears in the engine is wrong. A gear is any * symbol that is adjacent to exactly two part numbers. Its gear ratio is the result of multiplying those two numbers together.

This time, you need to find the gear ratio of every gear and add them all up so that the engineer can figure out which gear needs to be replaced.

Consider the same engine schematic again:
```
467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598..
```
In this schematic, there are two gears. The first is in the top left; it has part numbers 467 and 35, so its gear ratio is 16345. The second gear is in the lower right; its gear ratio is 451490. (The * adjacent to 617 is not a gear because it is only adjacent to one part number.) Adding up all of the gear ratios produces 467835.

What is the sum of all of the gear ratios in your engine schematic?

**AI Prompt**

if i want to alter the code above to keep track of four lines instead of three lines, how should i do so ?

**AI Response**

To track four lines instead of three, you can add another variable for the extra line. Here's how to modify the sliding window:

```python
curr_line = None
prev_line = None
prev_prev_line = None  # Add this new line
next_line = None

for line in lines:
    # Slide our window of 4 lines
    prev_prev_line = prev_line  # Shift everything down one more time
    prev_line = curr_line
    curr_line = next_line 
    next_line = line
```

Then when checking lines, you can include the prev_prev_line in your checks:
```python
for check_line in [prev_prev_line, prev_line, curr_line, next_line]:
    if not check_line: continue
    # rest of your checking code
```

Would you like me to explain more about how this sliding window works?

In [ ]:
import re
curr_line = None
prev_line = None
prev_prev_line = None
next_line = None
part_numbers = []

lines = inp.splitlines()
lines.append(None)
lines.append(None)

for line in lines:
    # Slide our window of 4 lines
    prev_prev_line = prev_line  # Shift everything down one more time
    prev_line = curr_line
    curr_line = next_line 
    next_line = line

    print("\nkicking off tri group")
    print(prev_line)
    print(curr_line)
    print(next_line)

    print("testing:", curr_line)
    if not curr_line: continue

    for match in re.finditer(r'\d+', curr_line):
        number = match.group()
        start_pos = match.start()
        end_pos = match.end()
        print(f"Line : number {number} from position {start_pos} to {end_pos}")
     
        # Check surrounding positions
        has_symbol = False
        
        # checking which are part numbers 
        for check_line in [prev_line, curr_line, next_line]:
            if not check_line: continue
            for pos in range(start_pos-1, end_pos+1):
                if 0<=pos<len(check_line):
                    char = check_line[pos]
                    print(f"  Checking {char} at pos {pos} in: {check_line}")
                    if char != '.' and not char.isdigit():
                        has_symbol = True
                        print("  Found symbol")

        print("Has symbol:", has_symbol)

        if has_symbol:
            part_numbers.append(number)
print (part_numbers)

result = sum(int(pn) for pn in part_numbers)
print (f"summed result: {result}")


kicking off tri group
None
None
.......358..........31.....339.....669.............598......328.....575......................447..650..............964...........692........
testing: None

kicking off tri group
None
.......358..........31.....339.....669.............598......328.....575......................447..650..............964...........692........
...............415..*.........@......*...627*...................945*.............144/.506............................*......514...*...150...
testing: .......358..........31.....339.....669.............598......328.....575......................447..650..............964...........692........
Line : number 358 from position 7 to 10
  Checking . at pos 6 in: .......358..........31.....339.....669.............598......328.....575......................447..650..............964...........692........
  Checking 3 at pos 7 in: .......358..........31.....339.....669.............598......328.....575......................447..650..............964.

In [ ]:
def is_part_number(prev_line, curr_line, next_line):
    # Check surrounding positions
    has_symbol = False
    
    # checking which are part numbers 
    for check_line in [prev_line, curr_line, next_line]:
        if not check_line: continue
        for pos in range(start_pos-1, end_pos+1):
            if 0<=pos<len(check_line):
                char = check_line[pos]
                print(f"  Checking {char} at pos {pos} in: {check_line}")
                if char != '.' and not char.isdigit():
                    has_symbol = True
                    print("  Found symbol")

    print("Has symbol:", has_symbol)
    return has_symbol

In [ ]:
import re
curr_line = None
prev_line = None
prev_prev_line = None
next_line = None
part_numbers = []

lines = inp.splitlines()
lines.append(None)
lines.append(None)

for (line_index, line) in enumerate(lines):
    # Slide our window of 4 lines
    prev_prev_line = prev_line  # Shift everything down one more time
    prev_line = curr_line
    curr_line = next_line 
    next_line = line

    print("\nkicking off tri group")
    print(prev_line)
    print(curr_line)
    print(next_line)

    print("testing:", curr_line)
    if not curr_line: continue

    for match in re.finditer(r'\d+', curr_line):
        number = match.group()
        start_pos = match.start()
        end_pos = match.end()
        print(f"Line : number {number} from position {start_pos} to {end_pos}")
     
        has_symbol = is_part_number(prev_line, curr_line, next_line)
        if has_symbol:
            part_numbers.append((number, start_pos, end_pos, line_index-1))

print (part_numbers)

result = sum(int(pn[0]) for pn in part_numbers)
print (f"summed result: {result}")


kicking off tri group
None
None
.......358..........31.....339.....669.............598......328.....575......................447..650..............964...........692........
testing: None

kicking off tri group
None
.......358..........31.....339.....669.............598......328.....575......................447..650..............964...........692........
...............415..*.........@......*...627*...................945*.............144/.506............................*......514...*...150...
testing: .......358..........31.....339.....669.............598......328.....575......................447..650..............964...........692........
Line : number 358 from position 7 to 10
  Checking . at pos 6 in: .......358..........31.....339.....669.............598......328.....575......................447..650..............964...........692........
  Checking 3 at pos 7 in: .......358..........31.....339.....669.............598......328.....575......................447..650..............964.

In [ ]:
len(part_numbers)

1064

In [ ]:
len(inp)

19739

In [ ]:
part_numbers[0]

('31', 20, 22, 0)

In [ ]:
inp

'.......358..........31.....339.....669.............598......328.....575......................447..650..............964...........692........\n...............415..*.........@......*...627*...................945*.............144/.506............................*......514...*...150...\n.........182..+.....873.756.......737........784..568....667..............258........./.........741...........707*....84........520.........\n..579...@.........$........*..........258.................*.........274..*.....739.......157./.....*580...........893.....696*........889...\n.....*.........875.........173.........*..................109...896*......959...*........=...677...........&636.........................$...\n......961..$............-...............907...569....#...........................756.....................................681................\n...........478...616.....30.....221*...............552.../33...258*343.....488........*682...526..*.........422...........&..........764....\n.....

In [ ]:
inp.splitlines()[0]

'.......358..........31.....339.....669.............598......328.....575......................447..650..............964...........692........'

In [ ]:
part_numbers[-1]

('833', 134, 137, 139)

In [ ]:
len(inp.splitlines())

140

In [ ]:
inp.splitlines()[-1]

'.............963......................542........734.....901...914..........843.............523..........818..................691.....833...'

In [ ]:
print(lines[0])
print(part_numbers[0])

.......358..........31.....339.....669.............598......328.....575......................447..650..............964...........692........
('31', 20, 22, 0)


In [ ]:
print(lines[-1])
print(part_numbers[-1])

None
('833', 134, 137, 139)


In [ ]:
part_numbers[-1], lines[part_numbers[-1][3]]

(('833', 134, 137, 139),
 '.............963......................542........734.....901...914..........843.............523..........818..................691.....833...')

In [ ]:
lines[-3:]

['.............963......................542........734.....901...914..........843.............523..........818..................691.....833...',
 None,
 None]

**AI Prompt**

any suggestions as to where to go next

**AI Response**

Looking at Part 2 of the problem, we need to:

1. Find all '*' symbols that are adjacent to exactly two part numbers
2. Calculate the gear ratio (multiply those two numbers together)
3. Sum all gear ratios

Here's a suggested approach:

1. First, let's modify our code to keep track of positions where '*' symbols appear:
```python
star_positions = []  # Will store (row, col) for each '*'
```

2. Then, for each part number we find, we should store its position and the line number:
```python
number_positions = []  # Will store (number, start_pos, end_pos, line_num)
```

3. Finally, we can check each '*' position to see which numbers are adjacent to it.

Would you like me to help you implement any of these steps?

**AI Prompt**

yes please

**AI Response**

Let's start with finding all the '*' positions. We can add this to our existing code:

```python
star_positions = []  # (row, col) for each '*'
number_positions = []  # (number, start_pos, end_pos, line_num)

for line_num, line in enumerate(lines):
    if line is None: continue
    
    # Find all '*' in this line
    for match in re.finditer(r'\*', line):
        star_pos = match.start()
        star_positions.append((line_num, star_pos))
    
    # Find all numbers in this line
    for match in re.finditer(r'\d+', line):
        number = match.group()
        start_pos = match.start()
        end_pos = match.end()
        number_positions.append((number, start_pos, end_pos, line_num))
```

Would you like to try this first part and see what we find? Then we can work on checking which numbers are adjacent to each star.

In [ ]:
star_positions = []  # (row, col) for each '*'
number_positions = []  # (number, start_pos, end_pos, line_num)

for line_num, line in enumerate(lines):
    if line is None: continue
    
    # Find all '*' in this line
    for match in re.finditer(r'\*', line):
        star_pos = match.start()
        star_positions.append((line_num, star_pos))
    
    # Find all numbers in this line
    for match in re.finditer(r'\d+', line):
        number = match.group()
        start_pos = match.start()
        end_pos = match.end()
        number_positions.append((number, start_pos, end_pos, line_num))

In [ ]:
star_positions

[(1, 20),
 (1, 37),
 (1, 44),
 (1, 67),
 (1, 117),
 (1, 130),
 (2, 113),
 (3, 27),
 (3, 58),
 (3, 73),
 (3, 99),
 (3, 125),
 (4, 5),
 (4, 39),
 (4, 67),
 (4, 80),
 (6, 35),
 (6, 66),
 (6, 86),
 (6, 98),
 (7, 75),
 (7, 92),
 (9, 8),
 (9, 44),
 (9, 132),
 (10, 18),
 (10, 40),
 (10, 97),
 (10, 104),
 (10, 112),
 (11, 4),
 (11, 66),
 (11, 92),
 (11, 119),
 (12, 59),
 (12, 106),
 (13, 12),
 (13, 49),
 (13, 85),
 (14, 70),
 (14, 94),
 (14, 110),
 (14, 135),
 (15, 21),
 (16, 89),
 (16, 122),
 (17, 35),
 (17, 70),
 (17, 115),
 (18, 48),
 (18, 56),
 (18, 62),
 (19, 39),
 (19, 103),
 (20, 119),
 (20, 128),
 (20, 136),
 (21, 107),
 (21, 111),
 (22, 9),
 (22, 42),
 (22, 133),
 (24, 64),
 (24, 117),
 (25, 30),
 (25, 40),
 (25, 83),
 (25, 124),
 (26, 14),
 (26, 45),
 (26, 48),
 (26, 55),
 (26, 73),
 (27, 21),
 (27, 100),
 (27, 132),
 (28, 6),
 (28, 37),
 (28, 81),
 (28, 111),
 (29, 97),
 (30, 5),
 (30, 40),
 (30, 113),
 (30, 134),
 (32, 54),
 (32, 66),
 (32, 130),
 (33, 9),
 (33, 24),
 (33, 29),
 (3

In [ ]:
number_positions

[('358', 7, 10, 0),
 ('31', 20, 22, 0),
 ('339', 27, 30, 0),
 ('669', 35, 38, 0),
 ('598', 51, 54, 0),
 ('328', 60, 63, 0),
 ('575', 68, 71, 0),
 ('447', 93, 96, 0),
 ('650', 98, 101, 0),
 ('964', 115, 118, 0),
 ('692', 129, 132, 0),
 ('415', 15, 18, 1),
 ('627', 41, 44, 1),
 ('945', 64, 67, 1),
 ('144', 81, 84, 1),
 ('506', 86, 89, 1),
 ('514', 124, 127, 1),
 ('150', 134, 137, 1),
 ('182', 9, 12, 2),
 ('873', 20, 23, 2),
 ('756', 24, 27, 2),
 ('737', 34, 37, 2),
 ('784', 45, 48, 2),
 ('568', 50, 53, 2),
 ('667', 57, 60, 2),
 ('258', 74, 77, 2),
 ('741', 96, 99, 2),
 ('707', 110, 113, 2),
 ('84', 118, 120, 2),
 ('520', 128, 131, 2),
 ('579', 2, 5, 3),
 ('258', 38, 41, 3),
 ('274', 68, 71, 3),
 ('739', 79, 82, 3),
 ('157', 89, 92, 3),
 ('580', 100, 103, 3),
 ('893', 114, 117, 3),
 ('696', 122, 125, 3),
 ('889', 134, 137, 3),
 ('875', 15, 18, 4),
 ('173', 27, 30, 4),
 ('109', 58, 61, 4),
 ('896', 64, 67, 4),
 ('959', 74, 77, 4),
 ('677', 93, 96, 4),
 ('636', 108, 111, 4),
 ('961', 6, 9, 

**AI Prompt**

ok whats next

**AI Response**

Now we need to write a function to check which numbers are adjacent to each star. Here's the approach:

```python
def find_adjacent_numbers(star_pos, star_row, number_positions):
    adjacent_numbers = []
    
    for number, start, end, num_row in number_positions:
        # Check if number is in adjacent row (including same row)
        if abs(num_row - star_row) <= 1:
            # Check if any part of the number is adjacent to star
            # Number positions that would be adjacent to star:
            # start-1 to end+1 should include star_pos
            if start-1 <= star_pos <= end:
                adjacent_numbers.append(int(number))
    
    return adjacent_numbers

# Then we can use it:
gear_ratios = []
for star_row, star_pos in star_positions:
    adjacent = find_adjacent_numbers(star_pos, star_row, number_positions)
    if len(adjacent) == 2:  # If exactly two numbers are adjacent
        gear_ratio = adjacent[0] * adjacent[1]
        gear_ratios.append(gear_ratio)
```

Would you like me to explain how this works, or would you like to try running it first?

In [ ]:
def find_adjacent_numbers(star_pos, star_row, number_positions):
    adjacent_numbers = []
    
    for number, start, end, num_row in number_positions:
        # Check if number is in adjacent row (including same row)
        if abs(num_row - star_row) <= 1:
            # Check if any part of the number is adjacent to star
            # Number positions that would be adjacent to star:
            # start-1 to end+1 should include star_pos
            if start-1 <= star_pos <= end:
                adjacent_numbers.append(int(number))
    
    return adjacent_numbers

# Then we can use it:
gear_ratios = []
for star_row, star_pos in star_positions:
    adjacent = find_adjacent_numbers(star_pos, star_row, number_positions)
    if len(adjacent) == 2:  # If exactly two numbers are adjacent
        gear_ratio = adjacent[0] * adjacent[1]
        gear_ratios.append(gear_ratio)

In [ ]:
gear_ratios

[27063,
 493053,
 491568,
 543375,
 80976,
 359840,
 631351,
 130788,
 72703,
 247422,
 429780,
 556419,
 234006,
 245504,
 558684,
 88494,
 20984,
 64698,
 7700,
 123107,
 79695,
 268110,
 385860,
 61920,
 66108,
 783520,
 275082,
 10728,
 136192,
 350784,
 6358,
 35280,
 755244,
 227265,
 957,
 335142,
 251064,
 77952,
 8020,
 62640,
 223496,
 759,
 5481,
 131480,
 521656,
 151776,
 61971,
 499155,
 121550,
 104252,
 637722,
 854496,
 309148,
 718256,
 2094,
 388692,
 456786,
 660387,
 62510,
 154475,
 462042,
 548120,
 303858,
 95600,
 144720,
 65520,
 45984,
 480936,
 122760,
 429048,
 535876,
 274839,
 580216,
 4640,
 220088,
 243302,
 259692,
 774158,
 524124,
 69384,
 696318,
 217998,
 189666,
 80109,
 275533,
 411768,
 707174,
 570605,
 26676,
 70741,
 49629,
 371700,
 29274,
 215100,
 403723,
 52390,
 54378,
 45150,
 5610,
 137268,
 146188,
 759360,
 35400,
 456918,
 17748,
 363196,
 65494,
 63726,
 26792,
 317703,
 660436,
 656580,
 266496,
 264960,
 18106,
 34832,
 265895,
 

In [ ]:
inp='''467..114..
...*......
..35..633.
......#...
617*......
.....+.58.
..592.....
......755.
...$.*....
.664.598..'''

In [ ]:
star_positions = []  # (row, col) for each '*'
number_positions = []  # (number, start_pos, end_pos, line_num)

for line_num, line in enumerate(inp.splitlines()):
    if line is None: continue
    
    # Find all '*' in this line
    for match in re.finditer(r'\*', line):
        star_pos = match.start()
        star_positions.append((line_num, star_pos))
    
    # Find all numbers in this line
    for match in re.finditer(r'\d+', line):
        number = match.group()
        start_pos = match.start()
        end_pos = match.end()
        number_positions.append((number, start_pos, end_pos, line_num))

In [ ]:
def find_adjacent_numbers(star_pos, star_row, number_positions):
    adjacent_numbers = []
    
    for number, start, end, num_row in number_positions:
        # Check if number is in adjacent row (including same row)
        if abs(num_row - star_row) <= 1:
            # Check if any part of the number is adjacent to star
            # Number positions that would be adjacent to star:
            # start-1 to end+1 should include star_pos
            if start-1 <= star_pos <= end:
                adjacent_numbers.append(int(number))
    
    return adjacent_numbers

# Then we can use it:
gear_ratios = []
for star_row, star_pos in star_positions:
    adjacent = find_adjacent_numbers(star_pos, star_row, number_positions)
    if len(adjacent) == 2:  # If exactly two numbers are adjacent
        gear_ratio = adjacent[0] * adjacent[1]
        gear_ratios.append(gear_ratio)
print (sum(gear_ratios))

467835


In [ ]:
sum(gear_ratios)

467835

In [ ]:
star_positions

[(1, 3), (4, 3), (8, 5)]

In [ ]:
number_positions

[('467', 0, 3, 0),
 ('114', 5, 8, 0),
 ('35', 2, 4, 2),
 ('633', 6, 9, 2),
 ('617', 0, 3, 4),
 ('58', 7, 9, 5),
 ('592', 2, 5, 6),
 ('755', 6, 9, 7),
 ('664', 1, 4, 9),
 ('598', 5, 8, 9)]

In [ ]:
from aocd import get_data
inp = get_data(day=3, year=2023)

In [ ]:
star_positions = []  # (row, col) for each '*'
number_positions = []  # (number, start_pos, end_pos, line_num)

for line_num, line in enumerate(inp.splitlines()):
    if line is None: continue
    
    # Find all '*' in this line
    for match in re.finditer(r'\*', line):
        star_pos = match.start()
        star_positions.append((line_num, star_pos))
    
    # Find all numbers in this line
    for match in re.finditer(r'\d+', line):
        number = match.group()
        start_pos = match.start()
        end_pos = match.end()
        number_positions.append((number, start_pos, end_pos, line_num))

In [ ]:
def find_adjacent_numbers(star_pos, star_row, number_positions):
    adjacent_numbers = []
    
    for number, start, end, num_row in number_positions:
        # Check if number is in adjacent row (including same row)
        if abs(num_row - star_row) <= 1:
            # Check if any part of the number is adjacent to star
            # Number positions that would be adjacent to star:
            # start-1 to end+1 should include star_pos
            if start-1 <= star_pos <= end:
                adjacent_numbers.append(int(number))
    
    return adjacent_numbers

# Then we can use it:
gear_ratios = []
for star_row, star_pos in star_positions:
    adjacent = find_adjacent_numbers(star_pos, star_row, number_positions)
    if len(adjacent) == 2:  # If exactly two numbers are adjacent
        gear_ratio = adjacent[0] * adjacent[1]
        gear_ratios.append(gear_ratio)
print (sum(gear_ratios))

84883664
